# Generated by Django 2.2.5 on 2021-05-29 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_loggedinuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedinuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
