# Generated by Django 3.2.3 on 2021-05-29 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0003_auto_20210529_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='Purpose_Of_Meeting',
        ),
        migrations.AddField(
            model_name='event',
            name='Host_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='Meeting_ClientID',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='Meeting_ClientName',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='Meeting_Link',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='Meeting_Type',
            field=models.CharField(choices=[('Interview', 'Interview'), ('FormalMeeting', 'Formal Meeting'), ('Annual General Meeting', 'Annual General Meeting'), ('Statutory Meeting', 'Statutory Meeting'), ('Board Meeting', 'Board Meeting'), ('Informal Meeting', 'Informal Meeting')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
