# Generated by Django 3.2.4 on 2021-06-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
