# Generated by Django 3.2.4 on 2021-06-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_delete_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
