# Generated by Django 3.2.3 on 2021-06-15 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0009_alter_event_confirm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='confirm',
            new_name='conf',
        ),
        migrations.AlterField(
            model_name='confirm',
            name='confirm',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='cal.event'),
        ),
    ]
