# Generated by Django 3.2.3 on 2021-06-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0011_auto_20210615_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Confirm',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Confirm',
        ),
    ]
