# Generated by Django 3.2.3 on 2021-06-20 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0013_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirm',
            name='event_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cal.event'),
            preserve_default=False,
        ),
    ]
