# Generated by Django 3.2.3 on 2021-06-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0014_confirm_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm',
            name='event_name',
        ),
    ]
