# Generated by Django 3.2.3 on 2021-06-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0015_remove_confirm_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='confirm',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
